import type { ProjectCard } from "@/apis/projects/projects.type";
import type { Company } from "./company";

export const EVENT_PROJECT_DATA: Record<Company, ProjectCard[]> = {
  naver: [
    {
      id: 98,
      title: "직고래",
      summary: "🐳 조직 내에서 중고 거래를! 직고래",
      techStacks: [
        "reactNative",
        "recoil",
        "axios",
        "typescript",
        "websocket",
        "oauth2",
        "java",
        "junit5",
        "springboot",
        "jpa",
        "restdocs",
        "mongodb",
        "mariadb",
        "flyway",
        "slf4j",
        "querydsl",
        "ec2",
        "nginx",
        "firebase",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-jikgorae-1.png",
      isLoved: false,
      loves: 0,
      views: 28,
    },
    {
      id: 87,
      title: "펀잇",
      summary:
        "궁금해? 맛있을걸? 먹어봐!\n🍙 편의점 음식 리뷰 & 꿀조합 공유 서비스 🍙",
      techStacks: [
        "java",
        "springboot",
        "jpa",
        "mysql",
        "h2",
        "junit5",
        "swagger",
        "oauth2",
        "typescript",
        "react",
        "webpack",
        "tanstackQuery",
        "styledComponents",
        "storybook",
        "msw",
        "jest",
        "ec2",
        "s3",
        "cloudfront",
        "githubAction",
        "jenkins",
        "nginx",
        "prometheus",
        "grafana",
        "babel",
        "reacttestinglibrary",
        "prettier",
        "reactRouter",
        "googleAnalytics",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%ED%8E%80%EC%9E%87-%EB%8B%A4%EB%A1%9C+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 29,
    },
    {
      id: 75,
      title: "터놓고",
      summary:
        "면담은 찐하게, 예약은 손쉽게! 올인원 면담 예약 서비스 터놓고 💖",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "storybook",
        "styledComponents",
        "githubAction",
        "jenkins",
        "ec2",
        "nginx",
        "java",
        "springboot",
        "jpa",
        "mysql",
        "junit5",
        "restdocs",
        "restassured",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-ternoko-1.jpg",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 74,
      title: "코드잽",
      summary: "나만의 코드 템플릿을 잽(zap)싸게 저장하고 공유하는 서비스",
      techStacks: [
        "jest",
        "webpack",
        "javascript",
        "storybook",
        "react",
        "typescript",
        "prettier",
        "msw",
        "java",
        "spring",
        "springboot",
        "jpa",
        "lombok",
        "mysql",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3%E1%84%8C%E1%85%A2%E1%86%B8+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 13,
    },
    {
      id: 66,
      title: "행동대장",
      summary: "행동대장들의 정산을 간편하게💰행동대장",
      techStacks: [
        "storybook",
        "jest",
        "webpack",
        "tanstackQuery",
        "typescript",
        "react",
        "msw",
        "java",
        "spring",
        "springboot",
        "jpa",
        "jwt",
        "lombok",
        "h2",
        "mysql",
        "mockito",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%92%E1%85%A2%E1%86%BC%E1%84%83%E1%85%A9%E1%86%BC%E1%84%83%E1%85%A2%E1%84%8C%E1%85%A1%E1%86%BC+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 6,
    },
    {
      id: 57,
      title: "공식",
      summary: "공식(공유해줘 너의 지식) : 우테코 크루들을 위한 질문 게시판",
      techStacks: [
        "react",
        "javascript",
        "typescript",
        "emotion",
        "tanstackQuery",
        "recoil",
        "webpack",
        "babel",
        "storybook",
        "reacttestinglibrary",
        "jest",
        "msw",
        "prettier",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "querydsl",
        "restdocs",
        "slf4j",
        "restassured",
        "mysql",
        "h2",
        "flyway",
        "junit5",
        "aws",
        "ec2",
        "cloudwatch",
        "nginx",
        "jenkins",
        "githubAction",
        "sonarqube",
        "jacoco",
        "jwt",
        "redis",
        "ngrinder",
        "grafana",
        "prometheus",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-gongseek-1.png",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 56,
      title: "CoReA",
      summary: "코드 리뷰 파트너 자동 매칭 플랫폼 CoReA로 완성하는 성장의 퍼즐",
      techStacks: [
        "java",
        "spring",
        "springboot",
        "jpa",
        "h2",
        "mysql",
        "gradle",
        "lombok",
        "junit5",
        "mockito",
        "aws",
        "jest",
        "react",
        "msw",
        "tanstackQuery",
        "typescript",
        "styledComponents",
        "storybook",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%8F%E1%85%A9%E1%84%85%E1%85%A6%E1%84%8B%E1%85%A1+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 8,
    },
    {
      id: 52,
      title: "깃-들다",
      summary: "💻 Github Repo 기반 개발 장려 SNS",
      techStacks: [
        "javascript",
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "storybook",
        "jest",
        "webpack",
        "aws",
        "ec2",
        "jenkins",
        "s3",
        "cloudfront",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "restdocs",
        "slf4j",
        "mariadb",
        "redis",
        "elasticSearch",
        "h2",
        "flyway",
        "mockito",
        "junit5",
        "cloudwatch",
        "docker",
        "nginx",
        "sonarqube",
        "jacoco",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-pickgit-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 13,
      title: "스타카토",
      summary: "🗺️ 지도 기반 일상 기록 서비스 스타카토",
      techStacks: [
        "java",
        "springboot",
        "gradle",
        "junit5",
        "mockito",
        "jpa",
        "mysql",
        "h2",
        "flyway",
        "githubAction",
        "aws",
        "docker",
        "cloudfront",
        "nginx",
        "kotlin",
        "hilt",
        "jetpack",
        "retrofit",
        "firebase",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%89%E1%85%B3%E1%84%90%E1%85%A1%E1%84%8F%E1%85%A1%E1%84%90%E1%85%A9+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 8,
    },
    {
      id: 10,
      title: "Babble",
      summary: "🌎 관심사 기반 빠른 게임 팀 매칭 서비스, Babble",
      techStacks: [
        "react",
        "sass",
        "storybook",
        "cypress",
        "webpack",
        "babel",
        "prettier",
        "axios",
        "ec2",
        "cloudfront",
        "s3",
        "cloudwatch",
        "docker",
        "mariadb",
        "githubAction",
        "sonarcloud",
        "sonarqube",
        "postgresql",
        "java",
        "springboot",
        "jpa",
        "flyway",
        "nginx",
        "redis",
        "gatling",
        "jacoco",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-babble-1.png",
      isLoved: false,
      loves: 0,
      views: 16,
    },
    {
      id: 9,
      title: "모락",
      summary: "🥳 모락: 모임을 즐겁게, 편하게!",
      techStacks: [
        "emotion",
        "jenkins",
        "aws",
        "sonarqube",
        "junit5",
        "restassured",
        "h2",
        "java",
        "gradle",
        "slf4j",
        "prometheus",
        "grafana",
        "mysql",
        "javascript",
        "nginx",
        "jpa",
        "springboot",
        "ngrinder",
        "spring",
        "restdocs",
        "cypress",
        "reacttestinglibrary",
        "storybook",
        "react",
        "webpack",
        "typescript",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-morak-1.png",
      isLoved: false,
      loves: 0,
      views: 10,
    },
    {
      id: 3,
      title: "찜꽁",
      summary:
        "공간을 한 눈에, 예약은 한 번에! 맞춤형 공간예약 서비스 제작 플랫폼 찜꽁입니다!",
      techStacks: [
        "webpack",
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "msw",
        "jest",
        "reacttestinglibrary",
        "storybook",
        "java",
        "springboot",
        "jpa",
        "oauth2",
        "apachezookeeper",
        "restdocs",
        "junit5",
        "restassured",
        "mockito",
        "slf4j",
        "kafka",
        "elasticSearch",
        "logstash",
        "kibana",
        "mysql",
        "flyway",
        "redis",
        "h2",
        "kubernetes",
        "docker",
        "nginx",
        "prometheus",
        "grafana",
        "aws",
        "ec2",
        "s3",
        "cloudwatch",
        "jenkins",
        "jacoco",
        "sonarqube",
        "cloudfront",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang1.png",
      isLoved: false,
      loves: 0,
      views: 19,
    },
  ],
  kakao: [
    {
      id: 83,
      title: "여기서 만나",
      summary: "👋　만나기 좋은 중간지점을 추천해주는 서비스",
      techStacks: [
        "java",
        "springboot",
        "jenkins",
        "mariadb",
        "redis",
        "restdocs",
        "junit5",
        "sonarqube",
        "ec2",
        "nginx",
        "javascript",
        "react",
        "webpack",
        "tanstackQuery",
        "styledComponents",
        "cypress",
        "githubAction",
        "babel",
        "reactRouter",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/nornag-see-1.png",
      isLoved: false,
      loves: 0,
      views: 32,
    },
    {
      id: 80,
      title: "투룻",
      summary: "To your route, touroot!",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "storybook",
        "tanstackQuery",
        "babel",
        "aws",
        "prettier",
        "msw",
        "emotion",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "lombok",
        "swagger",
        "junit5",
        "mockito",
        "jwt",
        "slf4j",
        "mysql",
        "h2",
        "flyway",
        "nginx",
        "docker",
        "githubAction",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%90%E1%85%AE%E1%84%85%E1%85%AE%E1%86%BA+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 12,
    },
    {
      id: 79,
      title: "다라쓰",
      summary:
        '🧩 웹 페이지 어디든 간편하게 추가하는 댓글 모듈 서비스 "다라쓰"',
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "webpack",
        "babel",
        "jest",
        "storybook",
        "s3",
        "cloudfront",
        "githubAction",
        "java",
        "springboot",
        "mariadb",
        "jpa",
        "ec2",
        "docker",
        "nginx",
        "kibana",
        "elasticSearch",
        "logstash",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-dara-1.png",
      isLoved: false,
      loves: 0,
      views: 21,
    },
    {
      id: 78,
      title: "땡쿠",
      summary: "당신의 마음을 전달하세요, 땡쿠 💌",
      techStacks: [
        "java",
        "nginx",
        "spring",
        "jpa",
        "restdocs",
        "junit5",
        "mockito",
        "h2",
        "mysql",
        "githubAction",
        "jenkins",
        "docker",
        "ec2",
        "springboot",
        "sonarqube",
        "k6",
        "grafana",
        "prometheus",
        "javascript",
        "react",
        "typescript",
        "tanstackQuery",
        "babel",
        "webpack",
        "axios",
        "emotion",
        "recoil",
        "prettier",
        "aws",
        "yarnberry",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-thankoo-1.svg",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 76,
      title: "놀토",
      summary: "부담없이 자랑하는 작고 소중한 내 프로젝트 🧸✨",
      techStacks: [
        "ec2",
        "cloudfront",
        "s3",
        "jenkins",
        "docker",
        "sonarqube",
        "flyway",
        "java",
        "junit5",
        "redis",
        "springboot",
        "jpa",
        "mariadb",
        "nginx",
        "react",
        "typescript",
        "styledComponents",
        "tanstackQuery",
        "express",
        "nodejs",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-nolto-1.png",
      isLoved: false,
      loves: 0,
      views: 13,
    },
    {
      id: 75,
      title: "터놓고",
      summary:
        "면담은 찐하게, 예약은 손쉽게! 올인원 면담 예약 서비스 터놓고 💖",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "storybook",
        "styledComponents",
        "githubAction",
        "jenkins",
        "ec2",
        "nginx",
        "java",
        "springboot",
        "jpa",
        "mysql",
        "junit5",
        "restdocs",
        "restassured",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-ternoko-1.jpg",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 72,
      title: "행록",
      summary: '장소 기반 여행 기록 서비스, "행록"⛱️',
      techStacks: [
        "babel",
        "typescript",
        "react",
        "prettier",
        "webpack",
        "java",
        "jpa",
        "slf4j",
        "h2",
        "mysql",
        "junit5",
        "springboot",
        "ec2",
        "cloudwatch",
        "s3",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%ED%96%89%EB%A1%9D+%EB%8B%A4%EB%A1%9C+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 12,
    },
    {
      id: 67,
      title: "모아모아",
      summary: '🪐 스터디를 "모아모아" 🪐',
      techStacks: [
        "junit5",
        "mockito",
        "nginx",
        "ec2",
        "s3",
        "k6",
        "grafana",
        "prometheus",
        "jacoco",
        "sonarqube",
        "githubAction",
        "typescript",
        "react",
        "tanstackQuery",
        "emotion",
        "storybook",
        "cypress",
        "webpack",
        "msw",
        "prettier",
        "java",
        "springboot",
        "gradle",
        "restdocs",
        "jpa",
        "mysql",
        "slf4j",
        "oauth2",
        "restassured",
        "h2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-moamoa-1.png",
      isLoved: false,
      loves: 0,
      views: 21,
    },
    {
      id: 58,
      title: "내편",
      summary: "내 마음을 편지로, 내 편 💌",
      techStacks: [
        "java",
        "gradle",
        "springboot",
        "spring",
        "jpa",
        "restdocs",
        "querydsl",
        "junit5",
        "restassured",
        "flyway",
        "mysql",
        "h2",
        "jwt",
        "oauth2",
        "slf4j",
        "nginx",
        "jenkins",
        "githubAction",
        "aws",
        "ec2",
        "cloudwatch",
        "sonarqube",
        "react",
        "typescript",
        "webpack",
        "babel",
        "tanstackQuery",
        "emotion",
        "storybook",
        "reacttestinglibrary",
        "msw",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-naepyeon-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 52,
      title: "깃-들다",
      summary: "💻 Github Repo 기반 개발 장려 SNS",
      techStacks: [
        "javascript",
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "storybook",
        "jest",
        "webpack",
        "aws",
        "ec2",
        "jenkins",
        "s3",
        "cloudfront",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "restdocs",
        "slf4j",
        "mariadb",
        "redis",
        "elasticSearch",
        "h2",
        "flyway",
        "mockito",
        "junit5",
        "cloudwatch",
        "docker",
        "nginx",
        "sonarqube",
        "jacoco",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-pickgit-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 51,
      title: "모모",
      summary: "한 눈에 참여하는 모임 서비스, '모두 모여라' 모모입니다.",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "msw",
        "tanstackQuery",
        "recoil",
        "jest",
        "emotion",
        "nginx",
        "jenkins",
        "aws",
        "ec2",
        "java",
        "spring",
        "springboot",
        "jpa",
        "restdocs",
        "querydsl",
        "jwt",
        "mysql",
        "h2",
        "jmeter",
        "junit5",
        "restassured",
        "oauth2",
        "sonarqube",
        "githubAction",
        "docker",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-momo-1.png",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 48,
      title: "PengCook",
      summary: "Social media for sharing world recipes",
      techStacks: [
        "kotlin",
        "java",
        "spring",
        "jacoco",
        "springboot",
        "jpa",
        "firebase",
        "mysql",
        "h2",
        "lombok",
        "mockito",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%91%E1%85%A6%E1%86%BC%E1%84%8F%E1%85%AE%E1%86%A8+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 11,
    },
    {
      id: 36,
      title: "크루루",
      summary: "복잡한 리크루팅 과정을 간소화하는 맞춤형 리크루팅 관리 솔루션",
      techStacks: [
        "storybook",
        "emotion",
        "tanstackQuery",
        "react",
        "typescript",
        "zustand",
        "webpack",
        "java",
        "spring",
        "springboot",
        "jpa",
        "jwt",
        "h2",
        "mysql",
        "lombok",
        "junit5",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%8F%E1%85%B3%E1%84%85%E1%85%AE%E1%84%85%E1%85%AE+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 35,
    },
    {
      id: 34,
      title: "공첵",
      summary: "📘 함께 사용하는 공간, 우리가 체크하자!",
      techStacks: [
        "typescript",
        "react",
        "tanstackQuery",
        "recoil",
        "emotion",
        "cypress",
        "webpack",
        "babel",
        "prettier",
        "java",
        "gradle",
        "spring",
        "springboot",
        "jpa",
        "restdocs",
        "junit5",
        "mockito",
        "restassured",
        "mysql",
        "slf4j",
        "ec2",
        "aws",
        "githubAction",
        "jenkins",
        "nginx",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-gongcheck-1.png",
      isLoved: false,
      loves: 0,
      views: 23,
    },
    {
      id: 29,
      title: "주절주절",
      summary:
        "술 알고 마시자! 알고 마시면 더 맛있는 술! 당신을 위한 술을 추천해드립니다.",
      techStacks: [
        "react",
        "typescript",
        "tanstackQuery",
        "emotion",
        "reacttestinglibrary",
        "springboot",
        "jpa",
        "querydsl",
        "flyway",
        "restdocs",
        "ec2",
        "docker",
        "jenkins",
        "aws",
        "sonarqube",
        "githubAction",
        "mysql",
        "elasticSearch",
        "nginx",
        "cloudfront",
        "prometheus",
        "grafana",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-jujul-1.png",
      isLoved: false,
      loves: 0,
      views: 10,
    },
    {
      id: 15,
      title: "달록",
      summary: "달력이 기록을 공유할 때, 달록 🌙",
      techStacks: [
        "typescript",
        "react",
        "webpack",
        "babel",
        "emotion",
        "tanstackQuery",
        "recoil",
        "reacttestinglibrary",
        "storybook",
        "jenkins",
        "githubAction",
        "nginx",
        "aws",
        "jwt",
        "msw",
        "java",
        "gradle",
        "spring",
        "springboot",
        "jpa",
        "slf4j",
        "junit5",
        "restassured",
        "mockito",
        "jacoco",
        "sonarqube",
        "h2",
        "mysql",
        "cloudwatch",
        "jmeter",
        "oauth2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-dallog-1.png",
      isLoved: false,
      loves: 0,
      views: 49,
    },
  ],
  line: [
    {
      id: 104,
      title: "새벽",
      summary: "당신의 마음, 새벽이 들어줄게요",
      techStacks: [
        "java",
        "vuejs",
        "javascript",
        "pwa",
        "springboot",
        "jpa",
        "nginx",
        "log4j2",
        "jenkins",
        "ec2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-saebyeok-1.svg",
      isLoved: false,
      loves: 0,
      views: 22,
    },
    {
      id: 49,
      title: "땅땅땅",
      summary:
        "경매를 통해 원하는 가격에 중고 물품을 사고팔 수 있는 가장 합리적인 거래 플랫폼입니다!",
      techStacks: [
        "kotlin",
        "retrofit",
        "glide",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "flyway",
        "h2",
        "mysql",
        "oauth2",
        "jwt",
        "junit5",
        "jacoco",
        "ec2",
        "nginx",
        "jmeter",
        "jenkins",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/daro-%EB%95%85%EB%95%85%EB%95%85+1.jpg\n",
      isLoved: false,
      loves: 0,
      views: 9,
    },
    {
      id: 35,
      title: "Thank You For",
      summary: "누구나 쉽게 창작자를 응원할 수 있는 간편 도네이션 서비스!",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "reacttestinglibrary",
        "storybook",
        "docker",
        "webpack",
        "recoil",
        "msw",
        "githubAction",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "restdocs",
        "mockito",
        "junit5",
        "mysql",
        "redis",
        "h2",
        "flyway",
        "ec2",
        "s3",
        "aws",
        "cloudfront",
        "cloudwatch",
        "nginx",
        "jenkins",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-tyf-1.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 26,
      title: "GPU 내껀데",
      summary: "딥러닝 학습 자동화 서비스",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "jest",
        "storybook",
        "java",
        "springboot",
        "mariadb",
        "javascript",
        "python",
        "elasticSearch",
        "aws",
        "s3",
        "docker",
        "jenkins",
        "nginx",
        "logstash",
        "kibana",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-gpu-1.png",
      isLoved: false,
      loves: 0,
      views: 11,
    },
  ],
  dangn: [
    {
      id: 85,
      title: "데벨업",
      summary: "개발자 취업 준비생을 위한 상호 성장 플랫폼, '데벨업'",
      techStacks: ["react", "typescript"],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%83%E1%85%A6%E1%84%87%E1%85%A6%E1%86%AF%E1%84%8B%E1%85%A5%E1%86%B8+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB1.png",
      isLoved: false,
      loves: 0,
      views: 17,
    },
    {
      id: 68,
      title: "보고 또 보고",
      summary:
        "🐸 보고 또 보고는 취준생, 학생을 위한 반복 학습 장려 서비스입니다.",
      techStacks: [
        "typescript",
        "react",
        "reacttestinglibrary",
        "java",
        "junit5",
        "mariadb",
        "jpa",
        "nginx",
        "jenkins",
        "sonarqube",
        "docker",
        "reactRouter",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-bogo-1.png",
      isLoved: false,
      loves: 0,
      views: 13,
    },
    {
      id: 5,
      title: "줍줍",
      summary: "사라지는 Slack 메세지, 우리가 주워줄게!",
      techStacks: [
        "typescript",
        "react",
        "webpack",
        "styledComponents",
        "tanstackQuery",
        "recoil",
        "storybook",
        "java",
        "spring",
        "springboot",
        "jpa",
        "restdocs",
        "querydsl",
        "mysql",
        "h2",
        "mockito",
        "junit5",
        "sonarqube",
        "jacoco",
        "githubAction",
        "aws",
        "nginx",
        "gradle",
        "slf4j",
        "prettier",
        "jmeter",
        "jenkins",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo6.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 4,
      title: "땅콩",
      summary:
        "심심풀이 땅콩처럼 가벼운 주제로 친구들과 즐기는 단체 대화주제 제공 서비스 🥜",
      techStacks: ["java", "springboot", "typescript", "javascript"],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/malone1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
  ],
  toss: [
    {
      id: 96,
      title: "트립드로우",
      summary: "나만의 여행을 그리다. ✈️",
      techStacks: [
        "java",
        "springboot",
        "jpa",
        "mysql",
        "ec2",
        "kotlin",
        "firebase",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%ED%8A%B8%EB%A6%BD%EB%93%9C%EB%A1%9C%EC%9A%B0-%EB%8B%A4%EB%A1%9C+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 16,
    },
    {
      id: 85,
      title: "데벨업",
      summary: "개발자 취업 준비생을 위한 상호 성장 플랫폼, '데벨업'",
      techStacks: ["react", "typescript"],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%83%E1%85%A6%E1%84%87%E1%85%A6%E1%86%AF%E1%84%8B%E1%85%A5%E1%86%B8+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB1.png",
      isLoved: false,
      loves: 0,
      views: 17,
    },
    {
      id: 80,
      title: "투룻",
      summary: "To your route, touroot!",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "storybook",
        "tanstackQuery",
        "babel",
        "aws",
        "prettier",
        "msw",
        "emotion",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "lombok",
        "swagger",
        "junit5",
        "mockito",
        "jwt",
        "slf4j",
        "mysql",
        "h2",
        "flyway",
        "nginx",
        "docker",
        "githubAction",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%90%E1%85%AE%E1%84%85%E1%85%AE%E1%86%BA+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 12,
    },
    {
      id: 78,
      title: "땡쿠",
      summary: "당신의 마음을 전달하세요, 땡쿠 💌",
      techStacks: [
        "java",
        "nginx",
        "spring",
        "jpa",
        "restdocs",
        "junit5",
        "mockito",
        "h2",
        "mysql",
        "githubAction",
        "jenkins",
        "docker",
        "ec2",
        "springboot",
        "sonarqube",
        "k6",
        "grafana",
        "prometheus",
        "javascript",
        "react",
        "typescript",
        "tanstackQuery",
        "babel",
        "webpack",
        "axios",
        "emotion",
        "recoil",
        "prettier",
        "aws",
        "yarnberry",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-thankoo-1.svg",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 74,
      title: "코드잽",
      summary: "나만의 코드 템플릿을 잽(zap)싸게 저장하고 공유하는 서비스",
      techStacks: [
        "jest",
        "webpack",
        "javascript",
        "storybook",
        "react",
        "typescript",
        "prettier",
        "msw",
        "java",
        "spring",
        "springboot",
        "jpa",
        "lombok",
        "mysql",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3%E1%84%8C%E1%85%A2%E1%86%B8+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 13,
    },
    {
      id: 72,
      title: "행록",
      summary: '장소 기반 여행 기록 서비스, "행록"⛱️',
      techStacks: [
        "babel",
        "typescript",
        "react",
        "prettier",
        "webpack",
        "java",
        "jpa",
        "slf4j",
        "h2",
        "mysql",
        "junit5",
        "springboot",
        "ec2",
        "cloudwatch",
        "s3",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%ED%96%89%EB%A1%9D+%EB%8B%A4%EB%A1%9C+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 12,
    },
    {
      id: 65,
      title: "스탬프크러쉬",
      summary: "카페 사장님과 고객을 위한 온라인 쿠폰 적립 및 관리 서비스",
      techStacks: [
        "react",
        "typescript",
        "tanstackQuery",
        "webpack",
        "styledComponents",
        "jest",
        "java",
        "jpa",
        "querydsl",
        "mockito",
        "restdocs",
        "slf4j",
        "h2",
        "mysql",
        "junit5",
        "springboot",
        "ec2",
        "cloudwatch",
        "s3",
        "jenkins",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%EC%8A%A4%ED%83%AC%ED%94%84%ED%81%AC%EB%9F%AC%EC%8B%9C+%EB%8B%A4%EB%A1%9C+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 6,
    },
    {
      id: 64,
      title: "꼭꼭",
      summary: "약속을 전달해요, 꼭꼭으로 간편하게!",
      techStacks: [
        "css",
        "javascript",
        "typescript",
        "react",
        "tanstackQuery",
        "reacttestinglibrary",
        "emotion",
        "webpack",
        "aws",
        "ec2",
        "jenkins",
        "nginx",
        "java",
        "springboot",
        "spring",
        "gradle",
        "jpa",
        "restdocs",
        "restassured",
        "junit5",
        "mockito",
        "jacoco",
        "sonarcloud",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-kkogkkog-1.png",
      isLoved: false,
      loves: 0,
      views: 23,
    },
    {
      id: 62,
      title: "코끼리끼리",
      summary: "함께 목표를 달성하고자 하는 사람들이 모이는 코끼리끼리 !",
      techStacks: [
        "react",
        "typescript",
        "tanstackQuery",
        "webpack",
        "styledComponents",
        "jest",
        "java",
        "jpa",
        "querydsl",
        "mockito",
        "restdocs",
        "slf4j",
        "h2",
        "mysql",
        "junit5",
        "springboot",
        "ec2",
        "cloudwatch",
        "s3",
        "jenkins",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%EC%BD%94%EB%81%BC%EB%A6%AC+%EB%8B%A4%EB%A1%9C+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 15,
    },
    {
      id: 58,
      title: "내편",
      summary: "내 마음을 편지로, 내 편 💌",
      techStacks: [
        "java",
        "gradle",
        "springboot",
        "spring",
        "jpa",
        "restdocs",
        "querydsl",
        "junit5",
        "restassured",
        "flyway",
        "mysql",
        "h2",
        "jwt",
        "oauth2",
        "slf4j",
        "nginx",
        "jenkins",
        "githubAction",
        "aws",
        "ec2",
        "cloudwatch",
        "sonarqube",
        "react",
        "typescript",
        "webpack",
        "babel",
        "tanstackQuery",
        "emotion",
        "storybook",
        "reacttestinglibrary",
        "msw",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-naepyeon-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 55,
      title: "카페인",
      summary: "실시간 전기자동차 충전소 지도 및 사용 통계 조회 서비스",
      techStacks: [
        "react",
        "typescript",
        "tanstackQuery",
        "webpack",
        "styledComponents",
        "storybook",
        "jest",
        "githubAction",
        "mysql",
        "springboot",
        "aws",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/darto-%EC%B9%B4%ED%8E%98%EC%9D%B8+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 54,
      title: "F12",
      summary: "개발자의 모든 도구, F12 💻",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "webpack",
        "storybook",
        "msw",
        "cypress",
        "reacttestinglibrary",
        "springboot",
        "java",
        "junit5",
        "oauth2",
        "jpa",
        "querydsl",
        "mysql",
        "restdocs",
        "restassured",
        "slf4j",
        "mockito",
        "aws",
        "ec2",
        "githubAction",
        "nginx",
        "jenkins",
        "sonarqube",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-f12-1.png",
      isLoved: false,
      loves: 0,
      views: 30,
    },
    {
      id: 53,
      title: "momo",
      summary: "만남 전 스트레스를 줄이고 즐거움만 챙기고 싶나요? 모모하세요!",
      techStacks: [
        "react",
        "tanstackQuery",
        "babel",
        "emotion",
        "storybook",
        "webpack",
        "typescript",
        "javascript",
        "java",
        "spring",
        "springboot",
        "lombok",
        "h2",
        "mysql",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%86%E1%85%A9%E1%84%86%E1%85%A9+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 7,
    },
    {
      id: 52,
      title: "깃-들다",
      summary: "💻 Github Repo 기반 개발 장려 SNS",
      techStacks: [
        "javascript",
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "storybook",
        "jest",
        "webpack",
        "aws",
        "ec2",
        "jenkins",
        "s3",
        "cloudfront",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "restdocs",
        "slf4j",
        "mariadb",
        "redis",
        "elasticSearch",
        "h2",
        "flyway",
        "mockito",
        "junit5",
        "cloudwatch",
        "docker",
        "nginx",
        "sonarqube",
        "jacoco",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-pickgit-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 47,
      title: "회고덕",
      summary: "⭐️ 함께 성장하는 회고 플랫폼 ⭐️",
      techStacks: [
        "jpa",
        "junit5",
        "mockito",
        "restassured",
        "mysql",
        "jenkins",
        "nginx",
        "githubAction",
        "flyway",
        "slf4j",
        "oauth2",
        "sonarqube",
        "jacoco",
        "swagger",
        "grafana",
        "prometheus",
        "react",
        "tanstackQuery",
        "msw",
        "cypress",
        "babel",
        "sass",
        "typescript",
        "webpack",
        "storybook",
        "recoil",
        "springboot",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-reviewduck-1.png",
      isLoved: false,
      loves: 0,
      views: 25,
    },
    {
      id: 41,
      title: "동글",
      summary:
        "📝같은 글을 한 번에 포스팅하자! 블로그 포스트 관리 툴, 동글✍️\n\n",
      techStacks: [],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/daro-%EB%8F%99%EA%B8%80+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 19,
    },
    {
      id: 35,
      title: "Thank You For",
      summary: "누구나 쉽게 창작자를 응원할 수 있는 간편 도네이션 서비스!",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "reacttestinglibrary",
        "storybook",
        "docker",
        "webpack",
        "recoil",
        "msw",
        "githubAction",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "restdocs",
        "mockito",
        "junit5",
        "mysql",
        "redis",
        "h2",
        "flyway",
        "ec2",
        "s3",
        "aws",
        "cloudfront",
        "cloudwatch",
        "nginx",
        "jenkins",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-tyf-1.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 33,
      title: "바톤",
      summary: "바톤, 너도 좋고 나도 좋은 코드 리뷰 중개 사이트",
      techStacks: [
        "typescript",
        "react",
        "tanstackQuery",
        "babel",
        "webpack",
        "msw",
        "storybook",
        "githubAction",
        "cypress",
        "springboot",
        "nginx",
        "querydsl",
        "mysql",
        "h2",
        "restdocs",
        "ec2",
        "cloudwatch",
        "slf4j",
        "docker",
        "flyway",
        "restassured",
        "mockito",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/daro-%EB%B0%94%ED%86%A4+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 13,
    },
    {
      id: 26,
      title: "GPU 내껀데",
      summary: "딥러닝 학습 자동화 서비스",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "jest",
        "storybook",
        "java",
        "springboot",
        "mariadb",
        "javascript",
        "python",
        "elasticSearch",
        "aws",
        "s3",
        "docker",
        "jenkins",
        "nginx",
        "logstash",
        "kibana",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-gpu-1.png",
      isLoved: false,
      loves: 0,
      views: 11,
    },
    {
      id: 25,
      title: "방끗",
      summary: "방끗; 방 구하기 끝! 그래서 방끗 😄",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "aws",
        "emotion",
        "storybook",
        "zustand",
        "tanstackQuery",
        "msw",
        "githubAction",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "junit5",
        "mockito",
        "h2",
        "mysql",
        "nginx",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%87%E1%85%A1%E1%86%BC%E1%84%81%E1%85%B3%E1%86%BA+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 15,
      title: "달록",
      summary: "달력이 기록을 공유할 때, 달록 🌙",
      techStacks: [
        "typescript",
        "react",
        "webpack",
        "babel",
        "emotion",
        "tanstackQuery",
        "recoil",
        "reacttestinglibrary",
        "storybook",
        "jenkins",
        "githubAction",
        "nginx",
        "aws",
        "jwt",
        "msw",
        "java",
        "gradle",
        "spring",
        "springboot",
        "jpa",
        "slf4j",
        "junit5",
        "restassured",
        "mockito",
        "jacoco",
        "sonarqube",
        "h2",
        "mysql",
        "cloudwatch",
        "jmeter",
        "oauth2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-dallog-1.png",
      isLoved: false,
      loves: 0,
      views: 49,
    },
    {
      id: 12,
      title: "속닥속닥",
      summary: "우리들만의 비밀 이야기🎋, 속닥속닥",
      techStacks: [
        "webpack",
        "babel",
        "typescript",
        "react",
        "tanstackQuery",
        "emotion",
        "jest",
        "reacttestinglibrary",
        "storybook",
        "msw",
        "java",
        "spring",
        "springboot",
        "jpa",
        "gradle",
        "junit5",
        "mockito",
        "restdocs",
        "aws",
        "nginx",
        "mysql",
        "h2",
        "git",
        "githubAction",
        "jenkins",
        "sonarqube",
        "grafana",
        "prometheus",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-sokdak-1.svg",
      isLoved: false,
      loves: 0,
      views: 7,
    },
    {
      id: 9,
      title: "모락",
      summary: "🥳 모락: 모임을 즐겁게, 편하게!",
      techStacks: [
        "emotion",
        "jenkins",
        "aws",
        "sonarqube",
        "junit5",
        "restassured",
        "h2",
        "java",
        "gradle",
        "slf4j",
        "prometheus",
        "grafana",
        "mysql",
        "javascript",
        "nginx",
        "jpa",
        "springboot",
        "ngrinder",
        "spring",
        "restdocs",
        "cypress",
        "reacttestinglibrary",
        "storybook",
        "react",
        "webpack",
        "typescript",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-morak-1.png",
      isLoved: false,
      loves: 0,
      views: 10,
    },
    {
      id: 4,
      title: "땅콩",
      summary:
        "심심풀이 땅콩처럼 가벼운 주제로 친구들과 즐기는 단체 대화주제 제공 서비스 🥜",
      techStacks: ["java", "springboot", "typescript", "javascript"],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/malone1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
  ],
  woowa: [
    {
      id: 104,
      title: "새벽",
      summary: "당신의 마음, 새벽이 들어줄게요",
      techStacks: [
        "java",
        "vuejs",
        "javascript",
        "pwa",
        "springboot",
        "jpa",
        "nginx",
        "log4j2",
        "jenkins",
        "ec2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-saebyeok-1.svg",
      isLoved: false,
      loves: 0,
      views: 22,
    },
    {
      id: 98,
      title: "직고래",
      summary: "🐳 조직 내에서 중고 거래를! 직고래",
      techStacks: [
        "reactNative",
        "recoil",
        "axios",
        "typescript",
        "websocket",
        "oauth2",
        "java",
        "junit5",
        "springboot",
        "jpa",
        "restdocs",
        "mongodb",
        "mariadb",
        "flyway",
        "slf4j",
        "querydsl",
        "ec2",
        "nginx",
        "firebase",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-jikgorae-1.png",
      isLoved: false,
      loves: 0,
      views: 28,
    },
    {
      id: 92,
      title: "요즘카페",
      summary:
        '"트렌디한 성수 지역의 카페를 손쉽게 탐색하는 서비스, ☕️ 요즘카페"',
      techStacks: [
        "react",
        "storybook",
        "babel",
        "msw",
        "webpack",
        "typescript",
        "java",
        "springboot",
        "jpa",
        "ec2",
        "mysql",
        "nginx",
        "docker",
        "prometheus",
        "grafana",
        "s3",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%EC%9A%94%EC%A6%98%EC%B9%B4%ED%8E%98-+daro+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 19,
    },
    {
      id: 84,
      title: "모우다",
      summary: "🤝 모여봐요, 우리의 다락방 (모우다)",
      techStacks: [
        "webpack",
        "jest",
        "storybook",
        "git",
        "javascript",
        "tanstackQuery",
        "react",
        "babel",
        "msw",
        "prettier",
        "java",
        "spring",
        "springboot",
        "lombok",
        "jwt",
        "jpa",
        "mysql",
        "h2",
        "nginx",
        "aws",
        "ec2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%86%E1%85%A9%E1%84%8B%E1%85%AE%E1%84%83%E1%85%A1+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB1.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 83,
      title: "여기서 만나",
      summary: "👋　만나기 좋은 중간지점을 추천해주는 서비스",
      techStacks: [
        "java",
        "springboot",
        "jenkins",
        "mariadb",
        "redis",
        "restdocs",
        "junit5",
        "sonarqube",
        "ec2",
        "nginx",
        "javascript",
        "react",
        "webpack",
        "tanstackQuery",
        "styledComponents",
        "cypress",
        "githubAction",
        "babel",
        "reactRouter",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/nornag-see-1.png",
      isLoved: false,
      loves: 0,
      views: 32,
    },
    {
      id: 80,
      title: "투룻",
      summary: "To your route, touroot!",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "storybook",
        "tanstackQuery",
        "babel",
        "aws",
        "prettier",
        "msw",
        "emotion",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "lombok",
        "swagger",
        "junit5",
        "mockito",
        "jwt",
        "slf4j",
        "mysql",
        "h2",
        "flyway",
        "nginx",
        "docker",
        "githubAction",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%90%E1%85%AE%E1%84%85%E1%85%AE%E1%86%BA+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 12,
    },
    {
      id: 79,
      title: "다라쓰",
      summary:
        '🧩 웹 페이지 어디든 간편하게 추가하는 댓글 모듈 서비스 "다라쓰"',
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "webpack",
        "babel",
        "jest",
        "storybook",
        "s3",
        "cloudfront",
        "githubAction",
        "java",
        "springboot",
        "mariadb",
        "jpa",
        "ec2",
        "docker",
        "nginx",
        "kibana",
        "elasticSearch",
        "logstash",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-dara-1.png",
      isLoved: false,
      loves: 0,
      views: 21,
    },
    {
      id: 78,
      title: "땡쿠",
      summary: "당신의 마음을 전달하세요, 땡쿠 💌",
      techStacks: [
        "java",
        "nginx",
        "spring",
        "jpa",
        "restdocs",
        "junit5",
        "mockito",
        "h2",
        "mysql",
        "githubAction",
        "jenkins",
        "docker",
        "ec2",
        "springboot",
        "sonarqube",
        "k6",
        "grafana",
        "prometheus",
        "javascript",
        "react",
        "typescript",
        "tanstackQuery",
        "babel",
        "webpack",
        "axios",
        "emotion",
        "recoil",
        "prettier",
        "aws",
        "yarnberry",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-thankoo-1.svg",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 75,
      title: "터놓고",
      summary:
        "면담은 찐하게, 예약은 손쉽게! 올인원 면담 예약 서비스 터놓고 💖",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "storybook",
        "styledComponents",
        "githubAction",
        "jenkins",
        "ec2",
        "nginx",
        "java",
        "springboot",
        "jpa",
        "mysql",
        "junit5",
        "restdocs",
        "restassured",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-ternoko-1.jpg",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 74,
      title: "코드잽",
      summary: "나만의 코드 템플릿을 잽(zap)싸게 저장하고 공유하는 서비스",
      techStacks: [
        "jest",
        "webpack",
        "javascript",
        "storybook",
        "react",
        "typescript",
        "prettier",
        "msw",
        "java",
        "spring",
        "springboot",
        "jpa",
        "lombok",
        "mysql",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3%E1%84%8C%E1%85%A2%E1%86%B8+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 13,
    },
    {
      id: 73,
      title: "레벨로그",
      summary: "레벨 인터뷰의 모든 것, 레벨로그",
      techStacks: [
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "webpack",
        "babel",
        "prettier",
        "msw",
        "jest",
        "storybook",
        "java",
        "springboot",
        "jpa",
        "restdocs",
        "junit5",
        "restassured",
        "mockito",
        "slf4j",
        "mariadb",
        "h2",
        "lombok",
        "oauth2",
        "ec2",
        "nginx",
        "jenkins",
        "githubAction",
        "jacoco",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-levellog-1.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 71,
      title: "CVI",
      summary: "💉 코로나19 백신 접종 후기 공유 플랫폼",
      techStacks: [
        "javascript",
        "react",
        "webpack",
        "babel",
        "emotion",
        "redux",
        "java",
        "springboot",
        "jpa",
        "restdocs",
        "slf4j",
        "querydsl",
        "oauth2",
        "ec2",
        "s3",
        "cloudfront",
        "cloudwatch",
        "nginx",
        "docker",
        "h2",
        "mysql",
        "flyway",
        "junit5",
        "restassured",
        "mockito",
        "cypress",
        "storybook",
        "jenkins",
        "jacoco",
        "sonarqube",
        "githubAction",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-cvi-1.png",
      isLoved: false,
      loves: 0,
      views: 16,
    },
    {
      id: 70,
      title: "리뷰미",
      summary: "자신이 어떤 개발자인지 파악하고 표현하는 데 도움을 주는 서비스",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "babel",
        "prettier",
        "tanstackQuery",
        "recoil",
        "jest",
        "aws",
        "githubAction",
        "java",
        "springboot",
        "gradle",
        "jpa",
        "mysql",
        "redis",
        "junit5",
        "flyway",
        "mockito",
        "docker",
        "grafana",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%85%E1%85%B5%E1%84%87%E1%85%B2%E1%84%86%E1%85%B5+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 11,
    },
    {
      id: 69,
      title: "티타임",
      summary: "서로를 채워주는 시간, 티타임 ☕️",
      techStacks: [
        "react",
        "typescript",
        "styledComponents",
        "webpack",
        "githubAction",
        "java",
        "springboot",
        "gradle",
        "jpa",
        "restdocs",
        "restassured",
        "mockito",
        "junit5",
        "slf4j",
        "ec2",
        "docker",
        "nginx",
        "jenkins",
        "sonarqube",
        "jacoco",
        "mysql",
        "redis",
        "h2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-teatime-1.jpg",
      isLoved: false,
      loves: 0,
      views: 17,
    },
    {
      id: 67,
      title: "모아모아",
      summary: '🪐 스터디를 "모아모아" 🪐',
      techStacks: [
        "junit5",
        "mockito",
        "nginx",
        "ec2",
        "s3",
        "k6",
        "grafana",
        "prometheus",
        "jacoco",
        "sonarqube",
        "githubAction",
        "typescript",
        "react",
        "tanstackQuery",
        "emotion",
        "storybook",
        "cypress",
        "webpack",
        "msw",
        "prettier",
        "java",
        "springboot",
        "gradle",
        "restdocs",
        "jpa",
        "mysql",
        "slf4j",
        "oauth2",
        "restassured",
        "h2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-moamoa-1.png",
      isLoved: false,
      loves: 0,
      views: 21,
    },
    {
      id: 66,
      title: "행동대장",
      summary: "행동대장들의 정산을 간편하게💰행동대장",
      techStacks: [
        "storybook",
        "jest",
        "webpack",
        "tanstackQuery",
        "typescript",
        "react",
        "msw",
        "java",
        "spring",
        "springboot",
        "jpa",
        "jwt",
        "lombok",
        "h2",
        "mysql",
        "mockito",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%92%E1%85%A2%E1%86%BC%E1%84%83%E1%85%A9%E1%86%BC%E1%84%83%E1%85%A2%E1%84%8C%E1%85%A1%E1%86%BC+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 6,
    },
    {
      id: 64,
      title: "꼭꼭",
      summary: "약속을 전달해요, 꼭꼭으로 간편하게!",
      techStacks: [
        "css",
        "javascript",
        "typescript",
        "react",
        "tanstackQuery",
        "reacttestinglibrary",
        "emotion",
        "webpack",
        "aws",
        "ec2",
        "jenkins",
        "nginx",
        "java",
        "springboot",
        "spring",
        "gradle",
        "jpa",
        "restdocs",
        "restassured",
        "junit5",
        "mockito",
        "jacoco",
        "sonarcloud",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-kkogkkog-1.png",
      isLoved: false,
      loves: 0,
      views: 23,
    },
    {
      id: 58,
      title: "내편",
      summary: "내 마음을 편지로, 내 편 💌",
      techStacks: [
        "java",
        "gradle",
        "springboot",
        "spring",
        "jpa",
        "restdocs",
        "querydsl",
        "junit5",
        "restassured",
        "flyway",
        "mysql",
        "h2",
        "jwt",
        "oauth2",
        "slf4j",
        "nginx",
        "jenkins",
        "githubAction",
        "aws",
        "ec2",
        "cloudwatch",
        "sonarqube",
        "react",
        "typescript",
        "webpack",
        "babel",
        "tanstackQuery",
        "emotion",
        "storybook",
        "reacttestinglibrary",
        "msw",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-naepyeon-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 57,
      title: "공식",
      summary: "공식(공유해줘 너의 지식) : 우테코 크루들을 위한 질문 게시판",
      techStacks: [
        "react",
        "javascript",
        "typescript",
        "emotion",
        "tanstackQuery",
        "recoil",
        "webpack",
        "babel",
        "storybook",
        "reacttestinglibrary",
        "jest",
        "msw",
        "prettier",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "querydsl",
        "restdocs",
        "slf4j",
        "restassured",
        "mysql",
        "h2",
        "flyway",
        "junit5",
        "aws",
        "ec2",
        "cloudwatch",
        "nginx",
        "jenkins",
        "githubAction",
        "sonarqube",
        "jacoco",
        "jwt",
        "redis",
        "ngrinder",
        "grafana",
        "prometheus",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-gongseek-1.png",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 55,
      title: "카페인",
      summary: "실시간 전기자동차 충전소 지도 및 사용 통계 조회 서비스",
      techStacks: [
        "react",
        "typescript",
        "tanstackQuery",
        "webpack",
        "styledComponents",
        "storybook",
        "jest",
        "githubAction",
        "mysql",
        "springboot",
        "aws",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/darto-%EC%B9%B4%ED%8E%98%EC%9D%B8+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 54,
      title: "F12",
      summary: "개발자의 모든 도구, F12 💻",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "webpack",
        "storybook",
        "msw",
        "cypress",
        "reacttestinglibrary",
        "springboot",
        "java",
        "junit5",
        "oauth2",
        "jpa",
        "querydsl",
        "mysql",
        "restdocs",
        "restassured",
        "slf4j",
        "mockito",
        "aws",
        "ec2",
        "githubAction",
        "nginx",
        "jenkins",
        "sonarqube",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-f12-1.png",
      isLoved: false,
      loves: 0,
      views: 30,
    },
    {
      id: 52,
      title: "깃-들다",
      summary: "💻 Github Repo 기반 개발 장려 SNS",
      techStacks: [
        "javascript",
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "storybook",
        "jest",
        "webpack",
        "aws",
        "ec2",
        "jenkins",
        "s3",
        "cloudfront",
        "java",
        "gradle",
        "springboot",
        "jpa",
        "restdocs",
        "slf4j",
        "mariadb",
        "redis",
        "elasticSearch",
        "h2",
        "flyway",
        "mockito",
        "junit5",
        "cloudwatch",
        "docker",
        "nginx",
        "sonarqube",
        "jacoco",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-pickgit-1.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 51,
      title: "모모",
      summary: "한 눈에 참여하는 모임 서비스, '모두 모여라' 모모입니다.",
      techStacks: [
        "react",
        "typescript",
        "webpack",
        "msw",
        "tanstackQuery",
        "recoil",
        "jest",
        "emotion",
        "nginx",
        "jenkins",
        "aws",
        "ec2",
        "java",
        "spring",
        "springboot",
        "jpa",
        "restdocs",
        "querydsl",
        "jwt",
        "mysql",
        "h2",
        "jmeter",
        "junit5",
        "restassured",
        "oauth2",
        "sonarqube",
        "githubAction",
        "docker",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-momo-1.png",
      isLoved: false,
      loves: 0,
      views: 20,
    },
    {
      id: 47,
      title: "회고덕",
      summary: "⭐️ 함께 성장하는 회고 플랫폼 ⭐️",
      techStacks: [
        "jpa",
        "junit5",
        "mockito",
        "restassured",
        "mysql",
        "jenkins",
        "nginx",
        "githubAction",
        "flyway",
        "slf4j",
        "oauth2",
        "sonarqube",
        "jacoco",
        "swagger",
        "grafana",
        "prometheus",
        "react",
        "tanstackQuery",
        "msw",
        "cypress",
        "babel",
        "sass",
        "typescript",
        "webpack",
        "storybook",
        "recoil",
        "springboot",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-reviewduck-1.png",
      isLoved: false,
      loves: 0,
      views: 25,
    },
    {
      id: 44,
      title: "괜찮을지도",
      summary:
        "내 관심사 지도를 만들고 함께 공유하는 참여형 데이터 매핑 서비스.",
      techStacks: [
        "java",
        "springboot",
        "jpa",
        "restdocs",
        "junit5",
        "restassured",
        "mockito",
        "mysql",
        "ec2",
        "jwt",
        "jmeter",
        "oauth2",
        "lombok",
        "docker",
        "s3",
        "nginx",
        "typescript",
        "react",
        "webpack",
        "zustand",
        "cypress",
        "jest",
        "storybook",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/daro-%EA%B4%9C%EC%B0%AE%EC%9D%84%EC%A7%80%EB%8F%84+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 24,
    },
    {
      id: 35,
      title: "Thank You For",
      summary: "누구나 쉽게 창작자를 응원할 수 있는 간편 도네이션 서비스!",
      techStacks: [
        "typescript",
        "react",
        "styledComponents",
        "reacttestinglibrary",
        "storybook",
        "docker",
        "webpack",
        "recoil",
        "msw",
        "githubAction",
        "java",
        "springboot",
        "jpa",
        "querydsl",
        "restdocs",
        "mockito",
        "junit5",
        "mysql",
        "redis",
        "h2",
        "flyway",
        "ec2",
        "s3",
        "aws",
        "cloudfront",
        "cloudwatch",
        "nginx",
        "jenkins",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-tyf-1.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 34,
      title: "공첵",
      summary: "📘 함께 사용하는 공간, 우리가 체크하자!",
      techStacks: [
        "typescript",
        "react",
        "tanstackQuery",
        "recoil",
        "emotion",
        "cypress",
        "webpack",
        "babel",
        "prettier",
        "java",
        "gradle",
        "spring",
        "springboot",
        "jpa",
        "restdocs",
        "junit5",
        "mockito",
        "restassured",
        "mysql",
        "slf4j",
        "ec2",
        "aws",
        "githubAction",
        "jenkins",
        "nginx",
        "sonarqube",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-gongcheck-1.png",
      isLoved: false,
      loves: 0,
      views: 23,
    },
    {
      id: 31,
      title: "Pokerogue Helper",
      summary: "포켓몬 배틀 도우미, Pokerogue Helper 🎮",
      techStacks: [
        "java",
        "spring",
        "springboot",
        "lombok",
        "mongodb",
        "restClient",
        "kotlin",
        "junit5",
        "retrofit",
        "jetpack",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%91%E1%85%A9%E1%84%8F%E1%85%A6%E1%86%BA%E1%84%86%E1%85%A9%E1%86%AB+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 17,
    },
    {
      id: 29,
      title: "주절주절",
      summary:
        "술 알고 마시자! 알고 마시면 더 맛있는 술! 당신을 위한 술을 추천해드립니다.",
      techStacks: [
        "react",
        "typescript",
        "tanstackQuery",
        "emotion",
        "reacttestinglibrary",
        "springboot",
        "jpa",
        "querydsl",
        "flyway",
        "restdocs",
        "ec2",
        "docker",
        "jenkins",
        "aws",
        "sonarqube",
        "githubAction",
        "mysql",
        "elasticSearch",
        "nginx",
        "cloudfront",
        "prometheus",
        "grafana",
        "ngrinder",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-jujul-1.png",
      isLoved: false,
      loves: 0,
      views: 10,
    },
    {
      id: 28,
      title: "반갑개",
      summary: "오늘 산책할 장소에 어떤 강아지들이 올지 확인할 수 있어요.",
      techStacks: [
        "java",
        "spring",
        "springboot",
        "typescript",
        "junit5",
        "mysql",
        "h2",
        "lombok",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/%E1%84%87%E1%85%A1%E1%86%AB%E1%84%80%E1%85%A1%E1%86%B8%E1%84%80%E1%85%A2+%E1%84%86%E1%85%A1%E1%86%AF%E1%84%85%E1%85%A9%E1%86%AB+1.png",
      isLoved: false,
      loves: 0,
      views: 21,
    },
    {
      id: 18,
      title: "Kerdy",
      summary:
        "컨퍼런스 및 행사에 함께할 팀원을 쉽게 찾고 연결하는 플랫폼, Kerdy.",
      techStacks: ["java", "springboot", "kotlin", "ec2"],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/daro+kerdy+%EC%8D%B8%EB%84%A4%EC%9D%BC.png",
      isLoved: false,
      loves: 0,
      views: 21,
    },
    {
      id: 15,
      title: "달록",
      summary: "달력이 기록을 공유할 때, 달록 🌙",
      techStacks: [
        "typescript",
        "react",
        "webpack",
        "babel",
        "emotion",
        "tanstackQuery",
        "recoil",
        "reacttestinglibrary",
        "storybook",
        "jenkins",
        "githubAction",
        "nginx",
        "aws",
        "jwt",
        "msw",
        "java",
        "gradle",
        "spring",
        "springboot",
        "jpa",
        "slf4j",
        "junit5",
        "restassured",
        "mockito",
        "jacoco",
        "sonarqube",
        "h2",
        "mysql",
        "cloudwatch",
        "jmeter",
        "oauth2",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-dallog-1.png",
      isLoved: false,
      loves: 0,
      views: 49,
    },
    {
      id: 10,
      title: "Babble",
      summary: "🌎 관심사 기반 빠른 게임 팀 매칭 서비스, Babble",
      techStacks: [
        "react",
        "sass",
        "storybook",
        "cypress",
        "webpack",
        "babel",
        "prettier",
        "axios",
        "ec2",
        "cloudfront",
        "s3",
        "cloudwatch",
        "docker",
        "mariadb",
        "githubAction",
        "sonarcloud",
        "sonarqube",
        "postgresql",
        "java",
        "springboot",
        "jpa",
        "flyway",
        "nginx",
        "redis",
        "gatling",
        "jacoco",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-babble-1.png",
      isLoved: false,
      loves: 0,
      views: 16,
    },
    {
      id: 5,
      title: "줍줍",
      summary: "사라지는 Slack 메세지, 우리가 주워줄게!",
      techStacks: [
        "typescript",
        "react",
        "webpack",
        "styledComponents",
        "tanstackQuery",
        "recoil",
        "storybook",
        "java",
        "spring",
        "springboot",
        "jpa",
        "restdocs",
        "querydsl",
        "mysql",
        "h2",
        "mockito",
        "junit5",
        "sonarqube",
        "jacoco",
        "githubAction",
        "aws",
        "nginx",
        "gradle",
        "slf4j",
        "prettier",
        "jmeter",
        "jenkins",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo6.png",
      isLoved: false,
      loves: 0,
      views: 18,
    },
    {
      id: 3,
      title: "찜꽁",
      summary:
        "공간을 한 눈에, 예약은 한 번에! 맞춤형 공간예약 서비스 제작 플랫폼 찜꽁입니다!",
      techStacks: [
        "webpack",
        "typescript",
        "react",
        "tanstackQuery",
        "styledComponents",
        "msw",
        "jest",
        "reacttestinglibrary",
        "storybook",
        "java",
        "springboot",
        "jpa",
        "oauth2",
        "apachezookeeper",
        "restdocs",
        "junit5",
        "restassured",
        "mockito",
        "slf4j",
        "kafka",
        "elasticSearch",
        "logstash",
        "kibana",
        "mysql",
        "flyway",
        "redis",
        "h2",
        "kubernetes",
        "docker",
        "nginx",
        "prometheus",
        "grafana",
        "aws",
        "ec2",
        "s3",
        "cloudwatch",
        "jenkins",
        "jacoco",
        "sonarqube",
        "cloudfront",
      ],
      thumbnailUrl:
        "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang1.png",
      isLoved: false,
      loves: 0,
      views: 19,
    },
  ],
};
