version: 0.2

cache:
  paths:
    - '/codebuild/output/.pnpm-store/**'  # pnpm store 디렉토리 전체 캐시
  # pnpm-lock.yaml은 캐시 경로에서 제거

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install -g pnpm
      - STORE_DIR=$(pnpm store path)          # 실제 store 경로 확인
      - echo "Using pnpm store-dir: $STORE_DIR"
      - pnpm config set store-dir $STORE_DIR  # store-dir 환경변수로 설정
      - pnpm install --frozen-lockfile --prefer-offline  # 캐시 재사용 우선 설치
      
  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --only-show-errors --exact-timestamps
      - aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION_ID" --paths "/index.html"


artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
