version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pwd
      - ls -al
      - cd frontend
      - npm install -g pnpm
      - pnpm install

  build:
    commands:
      - aws s3 rm s3://techcourse-project-2025/moaon/fe-dev-build/ --recursive
      - pnpm run build
      - pwd
      - ls -al dist

artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
