version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install -g pnpm
      - if [ -d /codebuild/output/.pnpm-store ]; then echo "Using cached pnpm store"; else mkdir -p /codebuild/output/.pnpm-store; fi
      - if [ -d node_modules ]; then echo "Using cached node_modules"; else mkdir -p node_modules; fi
      - pnpm install --frozen-lockfile --prefer-offline
      - pnpm store path

  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --only-show-errors --exact-timestamps
      - aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION_ID" --paths "/index.html"

cache:
  paths:
    - frontend/node_modules/**/*
    - /codebuild/output/.pnpm-store/**/*
