version: 0.2

cache:
  paths:
    - '/codebuild/output/.pnpm-store/v10/**'   
    - 'frontend/node_modules/**'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install -g pnpm
      - pnpm config set node-linker hoisted
      - pnpm config set store-dir /codebuild/output/.pnpm-store/v10
      - pnpm install --frozen-lockfile --prefer-offline
      - ls -alR node_modules || echo "node_modules 디렉토리 없음"

  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --only-show-errors --exact-timestamps
      - aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION_ID" --paths "/index.html"

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
