version: 0.2

cache:
  paths:
    - '.pnpm-store/**/*'
    # - '/codebuild/output/.pnpm-store/v10/**'    # pnpm store 전체 캐시
    # - 'frontend/node_modules/**'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - STORE_DIR=$(pnpm store path) 
      - echo "Setting pnpm store-dir to $STORE_DIR"
      - pnpm config set store-dir $STORE_DIR

      - ls -alR $STORE_DIR
      - ls -alR frontend/node_modules
      - cd frontend
      - npm install -g pnpm

      - pnpm config set store-dir .pnpm-store
      - pnpm install --frozen-lockfile
      - ls -alR $STORE_DIR
      - ls -alR frontend/node_modules

  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --only-show-errors --exact-timestamps
      - aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION_ID" --paths "/index.html"

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
