version: 0.2

cache:
  paths:
    - 'frontend/.pnpm-store/**/*'
    - 'frontend/pnpm-lock.yaml'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pwd
      - ls -al
      - cd frontend
      - npm install -g pnpm
      - pnpm store path
      - pnpm config set store-dir .pnpm-store
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm run build
      - pwd
      - ls -al dist
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --max-concurrent-requests 20 --size-only --only-show-errors --exact-timestamps

artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
