version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pwd
      - ls -al
      - cd frontend
      - npm install -g pnpm
      - pnpm install

  build:
    commands:
      - pnpm run build
      - pwd
      - ls -al dist
      - SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:6}
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/$SHORT_HASH/
      # - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete

artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
