version: 0.2

cache:
  paths:
    - '/codebuild/output/.pnpm-store/**/*'
    - 'frontend/pnpm-lock.yaml'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install -g pnpm
      - pnpm store path
      - pnpm config set store-dir /codebuild/output/.pnpm-store
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --only-show-errors --exact-timestamps --max-concurrent-requests 20

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
