version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install -g pnpm
      - PNPM_STORE_PATH=$(pnpm store path); if [ -d "$PNPM_STORE_PATH" ]; then echo "Using cached pnpm store"; else mkdir -p "$PNPM_STORE_PATH"; fi
      # - if [ -d node_modules ]; then echo "Using cached node_modules"; else mkdir -p node_modules; fi
      - pnpm config set store-dir "$PNPM_STORE_PATH"
      - pnpm install --frozen-lockfile --prefer-offline

  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --only-show-errors --exact-timestamps
      # - aws cloudfront create-invalidation --distribution-id "$CF_DISTRIBUTION_ID" --paths "/index.html"

# artifacts:
#   base-directory: frontend/dist
#   files:
#     - "**/*"

cache:
  paths:
    # - frontend/node_modules/**/*
    - /codebuild/output/.pnpm-store/**/*
