version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      # - corepack enable
      - if [ -f /usr/local/bin/pnpm ]; then echo "/usr/local/bin/pnpm 파일 있음"; else echo "/usr/local/bin/pnpm 파일 없음"; fi
      - if command -v pnpm >/dev/null 2>&1; then echo "pnpm 바이너리 있음: $(which pnpm)"; else echo "pnpm 바이너리 없음"; fi
      # - PNPM_STORE_PATH=$(pnpm store path); if [ -d "$PNPM_STORE_PATH" ]; then echo "Using cached pnpm store"; else mkdir -p "$PNPM_STORE_PATH"; fi
      # - pnpm config set store-dir "$PNPM_STORE_PATH"
      - if [ -d node_modules ]; then echo "Using cached node_modules"; else mkdir -p node_modules; fi
      - pnpm install --frozen-lockfile --prefer-offline

  build:
    commands:
      - pnpm run build
      - aws s3 sync ./dist s3://techcourse-project-2025/moaon/fe-dev-build/ --delete --only-show-errors --exact-timestamps

cache:
  paths:
    - frontend/node_modules/**/*
    - /usr/local/bin/pnpm
    # - /codebuild/output/.pnpm-store/**/*
