version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pwd
      - ls -al
      - cd frontend
      - npm install -g pnpm
      - pnpm install

  build:
    commands:
      - cd frontend
      - pnpm run build

artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
