services:
  app:
    image: ${DOCKERHUB_USERNAME}/moaon-backend:${IMAGE_TAG}
    container_name: moaon-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL_DEV: ${SPRING_DATASOURCE_URL_DEV}
      SPRING_DATASOURCE_USERNAME_DEV: ${SPRING_DATASOURCE_USERNAME_DEV}
      SPRING_DATASOURCE_PASSWORD_DEV: ${SPRING_DATASOURCE_PASSWORD_DEV}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
      OTEL_SERVICE_NAME: moaon-app-dev
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://10.0.3.18:4318
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME}
      SERVER_TOMCAT_THREADS_MAX: ${SERVER_TOMCAT_THREADS_MAX}
      SERVER_TOMCAT_THREADS_MAX_CONNECTIONS: ${SERVER_TOMCAT_THREADS_MAX_CONNECTIONS}
      SERVER_TOMCAT_THREADS_ACCEPT_COUNT: ${SERVER_TOMCAT_THREADS_ACCEPT_COUNT}
      SERVER_TOMCAT_THREADS_MIN_SPARE: ${SERVER_TOMCAT_THREADS_MIN_SPARE}
      SERVER_TOMCAT_CONNECTION_TIMEOUT: ${SERVER_TOMCAT_CONNECTION_TIMEOUT}
      GPT_API_KEY: ${GPT_API_KEY}

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host"
    volumes:
      - '/:/host:ro,rslave'

  promtail:
    image: grafana/promtail:2.9.0
    container_name: moaon-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
