services:
  app:
    image: ${DOCKERHUB_USERNAME}/moaon-backend:${IMAGE_TAG}
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      elastic:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: new
      SPRING_DATASOURCE_URL_NEW: ${SPRING_DATASOURCE_URL_NEW}
      SPRING_DATASOURCE_USERNAME_NEW: ${SPRING_DATASOURCE_USERNAME_NEW}
      SPRING_DATASOURCE_PASSWORD_NEW: ${SPRING_DATASOURCE_PASSWORD_NEW}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME}
      SERVER_TOMCAT_THREADS_MAX: ${SERVER_TOMCAT_THREADS_MAX}
      SERVER_TOMCAT_THREADS_MAX_CONNECTIONS: ${SERVER_TOMCAT_THREADS_MAX_CONNECTIONS}
      SERVER_TOMCAT_THREADS_ACCEPT_COUNT: ${SERVER_TOMCAT_THREADS_ACCEPT_COUNT}
      SERVER_TOMCAT_THREADS_MIN_SPARE: ${SERVER_TOMCAT_THREADS_MIN_SPARE}
      SERVER_TOMCAT_CONNECTION_TIMEOUT: ${SERVER_TOMCAT_CONNECTION_TIMEOUT}
      GPT_API_KEY: ${GPT_API_KEY}

  db:
    image: mysql:8.4
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
      LANG: C.UTF-8
    volumes:
      - db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elastic:
    build:
      context: .
    container_name: elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  db-data:
  es-data:
