services:
  nginx:
    image: nginx:stable-alpine
    container_name: moaon-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-web:/var/www/certbot
      - certbot-etc:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: moaon-certbot
    volumes:
      - certbot-web:/var/www/certbot
      - certbot-etc:/etc/letsencrypt

volumes:
  certbot-etc:
  certbot-web:
