services:
  db:
    image: mysql:8.4
    container_name: moaon-db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
      LANG: C.UTF-8
    volumes:
      - db-data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${DOCKERHUB_USERNAME}/moaon-backend:${IMAGE_TAG}
    container_name: moaon-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "moaon"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "dev-docker"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL_DEV: ${SPRING_DATASOURCE_URL_DEV}
      SPRING_DATASOURCE_USERNAME_DEV: ${SPRING_DATASOURCE_USERNAME_DEV}
      SPRING_DATASOURCE_PASSWORD_DEV: ${SPRING_DATASOURCE_PASSWORD_DEV}
      OTEL_SERVICE_NAME: moaon-app-dev
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://10.0.3.18:4318
    volumes:
      - log_data:/app/logs

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host"
    volumes:
      - '/:/host:ro,rslave'

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    command:
      - "--mysqld.username=${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASSWORD}"
      - "--mysqld.address=db:3306"
    depends_on:
      db:
        condition: service_healthy

  promtail:
    image: grafana/promtail:2.9.0
    container_name: moaon-promtail
    restart: unless-stopped
    volumes:
      - log_data:/var/log/app:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml

  selenium:
    image: selenium/standalone-chrome:139.0-20250909
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    platform: linux/amd64
    restart: unless-stopped

volumes:
  db-data:
  log_data:
