server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.3.18:3100/loki/api/v1/push

scrape_configs:
  - job_name: server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: server
          __path__: /var/log/app/*.log
