server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.3.18:3100/loki/api/v1/push
    external_labels:
      instance: ${INSTANCE_NAME}

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [ '__meta_docker_container_name' ]
        regex: '/(.*)'
        target_label: 'container'
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            thread: thread
            logger: logger
            msg: msg
            app: app
            env: env
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          app:
          env:
          level:
