import type { ProjectCard } from "@/apis/projects/projects.type";

export const 프론트엔드코치 = {
  id: 64,
  title: "꼭꼭",
  summary: "약속을 전달해요, 꼭꼭으로 간편하게!",
  techStacks: [
    "css",
    "javascript",
    "typescript",
    "react",
    "tanstackQuery",
    "reacttestinglibrary",
    "emotion",
    "webpack",
    "aws",
    "ec2",
    "jenkins",
    "nginx",
    "java",
    "springboot",
    "spring",
    "gradle",
    "jpa",
    "restdocs",
    "restassured",
    "junit5",
    "mockito",
    "jacoco",
    "sonarcloud",
  ],
  thumbnailUrl:
    "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/popo-kkogkkog-1.png",
  isLoved: false,
  loves: 0,
  views: 24,
} as ProjectCard;

export const 백엔드코치 = {
  id: 71,
  title: "CVI",
  summary: "💉 코로나19 백신 접종 후기 공유 플랫폼",
  techStacks: [
    "javascript",
    "react",
    "webpack",
    "babel",
    "emotion",
    "redux",
    "java",
    "springboot",
    "jpa",
    "restdocs",
    "slf4j",
    "querydsl",
    "oauth2",
    "ec2",
    "s3",
    "cloudfront",
    "cloudwatch",
    "nginx",
    "docker",
    "h2",
    "mysql",
    "flyway",
    "junit5",
    "restassured",
    "mockito",
    "cypress",
    "storybook",
    "jenkins",
    "jacoco",
    "sonarqube",
    "githubAction",
  ],
  thumbnailUrl:
    "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/moaon/projects/norang-cvi-1.png",
  isLoved: false,
  loves: 0,
  views: 16,
} as ProjectCard;
