spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL_DEV}
    username: ${SPRING_DATASOURCE_USERNAME_DEV}
    password: ${SPRING_DATASOURCE_PASSWORD_DEV}
  elasticsearch:
    uris: http://elastic:9200
