spring:
  profiles:
    default: local

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: "1"

  application:
    name: backend

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    health:
      show-details: never

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}

s3:
  bucket: ${S3_BUCKET}
  region: ${S3_REGION}

gpt:
  api-key: ${GPT_API_KEY}
