spring:
  application:
    name: moaon-app
  profiles:
    default: local
  datasource:
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:10}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:1800000}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: "1"

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      tomcat: true

server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: ${SERVER_TOMCAT_THREADS_MAX:200}
      max-connections: ${SERVER_TOMCAT_THREADS_MAX_CONNECTIONS:8192}
      accept-count: ${SERVER_TOMCAT_THREADS_ACCEPT_COUNT:100}
      min-spare: ${SERVER_TOMCAT_THREADS_MIN_SPARE:10}
    connection-timeout: ${SERVER_TOMCAT_CONNECTION_TIMEOUT:20000ms}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}

s3:
  bucket: ${S3_BUCKET}
  region: ${S3_REGION}

gpt:
  api-key: ${GPT_API_KEY}
