spring:
  profiles:
    default: local

  application:
    name: backend

  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
