name: 이슈 자동 담당자 지정

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assignAuthor:
    name: 이슈 작성자 담당자 지정
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 작성자 담당자 지정
        uses: technote-space/assign-author@v1

      - name: FE/BE 라벨 결정
        id: set_label
        run: |
          FE_MEMBERS=("eunoia-jaxson" "jin123457" "mlnwns" "wo-o29")
          BE_MEMBERS=("yesjuhee" "Minuring" "eueo8259" "minjae8563")
          AUTHOR="${{ github.actor }}"

          LABEL=""
          if printf '%s\n' "${FE_MEMBERS[@]}" | grep -qx "$AUTHOR"; then
            LABEL="FE"
          elif printf '%s\n' "${BE_MEMBERS[@]}" | grep -qx "$AUTHOR"; then
            LABEL="BE"
          fi

          echo "label=$LABEL" >> $GITHUB_OUTPUT

      - name: FE/BE 라벨 추가
        if: steps.set_label.outputs.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          labels: ${{ steps.set_label.outputs.label }}
