name: BE Dev CI

on:
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'backend/**'


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    needs: build
    
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        build-root-directory: backend
