name: BE Dev CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    if: |
      github.actor == 'yesjuhee' || 
      github.actor == 'Minuring' ||
      github.actor == 'eueo8259' ||
      github.actor == 'minjae8563'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper using cache
      run: ./gradlew build --build-cache

  check-dependencies-changed:
    needs: build

    outputs:
      dependencies-changed: ${{ steps.filter.outputs.dependencies }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Check if dependency files changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dependencies:
              - 'build.gradle'
              - 'settings.gradle'
              - '**/build.gradle'
              - '**/settings.gradle'

  dependency-submission:
    needs: check-dependencies-changed
    if: |
      needs.check-dependencies-changed.outputs.dependencies-changed == 'true' &&
      (
        github.actor == 'yesjuhee' || 
        github.actor == 'Minuring' ||
        github.actor == 'eueo8259' ||
        github.actor == 'minjae8563'
      )

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        build-root-directory: backend
