name: FE 빌드 테스트

on: [pull_request]

jobs:
  build:
    if: |
      github.actor == 'wo-o29' || 
      github.actor == 'eunoia-jaxson' ||
      github.actor == 'jin123457' ||
      github.actor == 'mlnwns'

    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 노드 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: pnpm 설치
        run: npm install -g pnpm

      - name: 의존성 설치
        run: pnpm install
        working-directory: ./frontend

      - name: 빌드 실행
        run: pnpm run build
        working-directory: ./frontend
