name: FE-Dev-Deploy

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      # 레포지토리의 코드를 컨테이너(작업 환경)로 가져오기
      # 이 작업을 해야 이후 스크립트에서 소스 코드 사용 가능
      - uses: actions/checkout@v3

      # rsync 설치
      # rsync: 리눅스/유닉스 환경에서 파일이나 디렉토리를 복사하고 동기화하는 데 특화된 명령어
      - name: Install rsync
        run: apk add --no-cache rsync
        working-directory: ./frontend

      # output 폴더 생성 및 소스 복사(build.sh 실행)
      # output 폴더를 만들고 원하는 파일/폴더 복사
      - name: creates output
        run: chmod +x ./build.sh && sh ./build.sh
        working-directory: ./frontend

      # 다른 레포지토리로 결과물 푸쉬
      # 포크된 레포지토리와 동기화
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: "frontend/output"
          destination-github-username: wo-o29
          destination-repository-name: 2025-moaon-fork
          user-email: ${{ secrets.WOOHYEOK_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop
